# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-bigquery-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: terraform-google-bigquery
    source:
      repo: https://github.com/terraform-google-modules/terraform-google-bigquery
      sourceType: git
  ui:
    input:
      variables:
        access:
          name: access
          title: Access
        dataset_id:
          name: dataset_id
          title: Dataset Id
          regexValidation: ^[a-zA-Z0-9_]{1,1000}[a-zA-Z0-9_]{0,24}$
          validation: Must contain only letters, numbers, or underscores. Must be 1024 characters or fewer.
        dataset_labels:
          name: dataset_labels
          title: Dataset Labels
        dataset_name:
          name: dataset_name
          title: Dataset Name
        default_partition_expiration_ms:
          name: default_partition_expiration_ms
          title: Default Partition Expiration Ms
        default_table_expiration_ms:
          name: default_table_expiration_ms
          title: Default Table Expiration Ms
        delete_contents_on_destroy:
          name: delete_contents_on_destroy
          title: Delete Contents On Destroy
        deletion_protection:
          name: deletion_protection
          title: Deletion Protection
        description:
          name: description
          title: Description
        encryption_key:
          name: encryption_key
          title: Encryption Key
        external_tables:
          name: external_tables
          title: External Tables
        location:
          name: location
          title: Location
        materialized_views:
          name: materialized_views
          title: Materialized Views
        max_time_travel_hours:
          name: max_time_travel_hours
          title: Max Time Travel Hours
        project_id:
          name: project_id
          title: Project Id
        resource_tags:
          name: resource_tags
          title: Resource Tags
        routines:
          name: routines
          title: Routines
        storage_billing_model:
          name: storage_billing_model
          title: Storage Billing Model
        tables:
          name: tables
          title: Tables
          level: 1
          altDefaults:
            - type: ALTERNATE_TYPE_DC
              value:
                - schema: "[{\"description\": \"A string type unique identifier\",\"mode\": \"NULLABLE\",\"name\": \"simpleId\",\"type\": \"STRING\"},{\"description\": \"A field to hold integer values\",\"mode\": \"NULLABLE\",\"name\": \"integerField\",\"type\": \"INTEGER\"},{\"description\": \"Data\",\"mode\": \"NULLABLE\",\"name\": \"data\",\"type\": \"STRING\"}]"
                  table_id: table-1
        views:
          name: views
          title: Views
